using ArgParse
function parse_cmd()
    cfg = ArgParseSettings()
    @add_arg_table cfg begin
        "--max"
        help = "maximum number"
        arg_type = Int
        default = 32
    end
    return parse_args(cfg)
end

function generate(io::IO, N_max::Int)
    # Header with update instructions
    println(io, "///")
    println(io, "/// @file solomon/util/impl/check_clause.hpp")
	println(io, "/// @brief Auto-generated macros for CHECK_CLAUSE macros up to $N_max inputs")
    println(io, "/// @note Generated by check_clause.jl with --max $N_max")
	println(io, "/// @note DO NOT EDIT THIS FILE MANUALLY - Regenerate with:")
	println(io, "///       cd solomon/util && julia jl/check_clause.jl --max $N_max")
    println(io, "///")
    println(io)
    println(io, "#if !defined(SOLOMON_UTIL_IMPL_CHECK_CLAUSE_HPP)")
	println(io, "#define SOLOMON_UTIL_IMPL_CHECK_CLAUSE_HPP")

    # generate CHECK_CLAUSE_N(...)
	println(io)
    for ii in 1:N_max
        print(io, "#define CHECK_CLAUSE_", ii, "(...) CHECK_CLAUSE(__VA_ARGS__)")
        if ii > 1
            print(io, " CHECK_CLAUSE_", ii - 1, "(ARGS_WITH_NUM(PICKUP_INTERNAL_DIRECTIVE_TAGS(__VA_ARGS__)) SOLOMON_APPEND_ARGS(PICKUP_INTERNAL_RETRIEVE_CLAUSE_CANDIDATE(PICKUP_INTERNAL_CLAUSE_ARGS(__VA_ARGS__))))")
        end
        println(io)
    end

    # New APPEND_CLAUSES with automatic clause sorting
    println(io)
    println(io, "///")
    println(io, "/// @brief Apply automatic clause sorting after checking valid clauses")
    println(io, "/// @note This moves AS_INDEPENDENT (and equivalents) to the front")
    println(io, "/// @warning Passing more than ", N_max, " clauses will cause a compile error:")
    println(io, "///          - Error message: 'CHECK_CLAUSE_*' was not declared in this scope")
    println(io, "///          - To fix: cd solomon/util && julia jl/check_clause.jl --max N")
    println(io, "///                   (where N >= your clause count)")
    println(io, "///")
    println(io, "#define APPEND_CLAUSES(...) SORT_AND_OUTPUT(CHECK_CLAUSE_", N_max, "(__VA_ARGS__))")
    # Original APPEND_CLAUSES without sorting (kept as comment for reference)
    println(io, "// #define APPEND_CLAUSES(...) CHECK_CLAUSE_", N_max, "(__VA_ARGS__)")

	println(io)
    println(io, "#endif // !defined(SOLOMON_UTIL_IMPL_CHECK_CLAUSE_HPP)")
end

function main()
    # read options
    argv = parse_cmd()
    N_max = argv["max"]

	output = "impl/check_clause.hpp"
	output_dir = dirname(output)
	if !isdir(output_dir)
		mkpath(output_dir)
	end

	open(output, "w") do io
		generate(io, N_max)
	end
end

main()
