using ArgParse
function parse_cmd()
    cfg = ArgParseSettings()
    @add_arg_table cfg begin
        "--max"
        help = "maximum number"
        arg_type = Int
        default = 1024
    end
    return parse_args(cfg)
end

function generate(io::IO, N_max::Int)
    # Header with update instructions
    println(io, "///")
    println(io, "/// @file solomon/util/impl/num_args.hpp")
	println(io, "/// @brief Auto-generated macros for SOLOMON_INTERNAL_NUM_ARGS macros up to $N_max inputs")
    println(io, "/// @note Generated by num_args.jl with --max $N_max")
	println(io, "/// @note DO NOT EDIT THIS FILE MANUALLY - Regenerate with:")
	println(io, "///       cd solomon/util && julia jl/num_args.jl --max $N_max")
    println(io, "///")
    println(io)
    println(io, "#if !defined(SOLOMON_UTIL_IMPL_NUM_ARGS_HPP)")
	println(io, "#define SOLOMON_UTIL_IMPL_NUM_ARGS_HPP")

    # generate SOLOMON_INTERNAL_NUM_ARGS_IMPL(...)
	println(io)
    println(io, "///")
	println(io, "/// @note implementation is copied from http://stackoverflow.com/a/26685339/213871 (answer in stack overflow by Francesco Pretto)")
    println(io, "///")
    print(io, "#define SOLOMON_INTERNAL_NUM_ARGS_IMPL(")
    for ii in 0:N_max
        print(io, "_", ii, ", ")
    end
    println(io, "N, ...) N")

    # generate SOLOMON_INTERNAL_NUM_ARGS(...)
	println(io)
    println(io, "///")
	println(io, "/// @note implementation is copied from http://stackoverflow.com/a/26685339/213871 (answer in stack overflow by Francesco Pretto)")
    println(io, "///")
    print(io, "#define SOLOMON_INTERNAL_NUM_ARGS(...) SOLOMON_INTERNAL_NUM_ARGS_IMPL(0, ##__VA_ARGS__")
    for ii in N_max:-1:0
        print(io, ", ", ii)
    end
    println(io, ")")

    # Add comment about exceeding the limit
    println(io)
    println(io, "///")
    println(io, "/// @note SOLOMON_INTERNAL_NUM_ARGS can count up to $N_max arguments")
    println(io, "///       If you need to count more arguments:")
    println(io, "///       - Run: cd solomon/util && julia jl/num_args.jl --max N")
    println(io, "///              (where N >= your required count)")
    println(io, "///")

	println(io)
    println(io, "#endif // !defined(SOLOMON_UTIL_IMPL_NUM_ARGS_HPP)")
end

function main()
    # read options
    argv = parse_cmd()
    N_max = argv["max"]

	output = "impl/num_args.hpp"
	output_dir = dirname(output)
	if !isdir(output_dir)
		mkpath(output_dir)
	end

	open(output, "w") do io
		generate(io, N_max)
	end
end

main()
