using ArgParse
function parse_cmd()
    cfg = ArgParseSettings()
    @add_arg_table cfg begin
        "--max"
        help = "maximum number"
        arg_type = Int
        default = 99
    end
    return parse_args(cfg)
end

function generate(io::IO, N_max::Int)
    # Header with update instructions
    println(io, "///")
    println(io, "/// @file solomon/util/impl/pickup_clause.hpp")
	println(io, "/// @brief Auto-generated macros for CHECK_CLAUSE macros up to $N_max inputs")
    println(io, "/// @note Generated by pickup_clause.jl with --max $N_max")
	println(io, "/// @note DO NOT EDIT THIS FILE MANUALLY - Regenerate with:")
	println(io, "///       cd solomon/util && julia jl/pickup_clause.jl --max $N_max")
    println(io, "///")
    println(io)
    println(io, "#if !defined(SOLOMON_UTIL_IMPL_PICKUP_CLAUSE_HPP)")
	println(io, "#define SOLOMON_UTIL_IMPL_PICKUP_CLAUSE_HPP")

    # generate PICKUP_INTERNAL_FLAG_MATCHING_N(...)
	println(io)
    println(io, "#define PICKUP_INTERNAL_FLAG_MATCHING_0(directive_tag) 0")
    println(io, "#define PICKUP_INTERNAL_FLAG_MATCHING_1(directive_tag, clause_tag) PICKUP_INTERNAL_BITOR_0(UTIL_CLOAK_EQUAL(directive_tag, clause_tag))")
    for ii in 2:N_max
        println(io, "#define PICKUP_INTERNAL_FLAG_MATCHING_", ii, "(directive_tag, clause_tag, ...) PICKUP_INTERNAL_BITOR(UTIL_CLOAK_EQUAL(directive_tag, clause_tag))(PICKUP_INTERNAL_FLAG_MATCHING_", ii - 1, "(directive_tag, __VA_ARGS__))")
    end

	# generate PICKUP_INTERNAL_EXPAND_FLAGS_N(...)
	println(io)
    println(io, "#define PICKUP_INTERNAL_EXPAND_FLAGS_1(...) PICKUP_INTERNAL_FLAG_MATCHING(__VA_ARGS__)")
    for ii in 2:N_max
        println(io, "#define PICKUP_INTERNAL_EXPAND_FLAGS_", ii, "(...) PICKUP_INTERNAL_BITOR(PICKUP_INTERNAL_EXPAND_FLAGS_1(EXTRACT_ARGS_1(__VA_ARGS__), RETRIEVE_ARGS_", ii, "(__VA_ARGS__)))(PICKUP_INTERNAL_EXPAND_FLAGS_", ii - 1, "(RETRIEVE_ARGS_1(__VA_ARGS__)))")
    end

    # generate PICKUP_CLAUSE_N(...)
	println(io)
    for ii in 1:N_max
        print(io, "#define PICKUP_CLAUSE_", ii, "(")
        for jj in 1:ii
            print(io, "tag", jj, ", ")
        end
        print(io, "clause, ...) APPEND_CLAUSE(PICKUP_INTERNAL_EXPAND_FLAGS_", ii, "(")
        for jj in 1:ii
            print(io, "tag", jj, ", ")
        end
        println(io, "__VA_ARGS__), clause)")
    end

	println(io)
    println(io, "#endif // !defined(SOLOMON_UTIL_IMPL_PICKUP_CLAUSE_HPP)")
end

function main()
    # read options
    argv = parse_cmd()
    N_max = argv["max"]

	output = "impl/pickup_clause.hpp"
	output_dir = dirname(output)
	if !isdir(output_dir)
		mkpath(output_dir)
	end

	open(output, "w") do io
		generate(io, N_max)
	end
end

main()
