using ArgParse
function parse_cmd()
    cfg = ArgParseSettings()
    @add_arg_table cfg begin
        "--max"
        help = "maximum number"
        arg_type = Int
        default = 128
    end
    return parse_args(cfg)
end

function generate(io::IO, N_max::Int)
    # Header with update instructions
    println(io, "///")
    println(io, "/// @file solomon/util/impl/retrieve_args.hpp")
	println(io, "/// @brief Auto-generated macros for retrieve_ARGS macros up to $N_max inputs")
    println(io, "/// @note Generated by retrieve_args.jl with --max $N_max")
	println(io, "/// @note DO NOT EDIT THIS FILE MANUALLY - Regenerate with:")
	println(io, "///       cd solomon/util && julia jl/retrieve_args.jl --max $N_max")
    println(io, "///")
    println(io)
    println(io, "#if !defined(SOLOMON_UTIL_IMPL_RETRIEVE_ARGS_HPP)")
	println(io, "#define SOLOMON_UTIL_IMPL_RETRIEVE_ARGS_HPP")

    # generate EXTRACT_ARGS_N(...)
	println(io)
    for ii in 0:N_max
        print(io, "#define EXTRACT_ARGS_", ii, "(")
        for jj in 1:ii
            print(io, "arg", jj, ", ")
        end
        print(io, "...) ")
        for jj in 1:ii
            print(io, "arg", jj)
            if jj < ii
                print(io, ", ")
            end
        end
        println(io)
    end

    # generate RETRIEVE_ARGS_N(...)
	println(io)
    for ii in 0:N_max
        print(io, "#define RETRIEVE_ARGS_", ii, "(")
        for jj in 1:ii
            print(io, "arg", jj, ", ")
        end
        println(io, "...) __VA_ARGS__")
    end

    # Add comment about exceeding the limit
    println(io)
    println(io, "///")
    println(io, "/// @warning Using EXTRACT_ARGS_N or RETRIEVE_ARGS_N with N > $N_max will cause a compile error:")
    println(io, "///          - Error message: 'EXTRACT_ARGS_$(N_max + 1)' or 'RETRIEVE_ARGS_$(N_max + 1)' was not declared")
    println(io, "///          - To fix: cd solomon/util && julia jl/extract_args.jl --max N")
    println(io, "///                   (where N >= your required argument count)")
    println(io, "///")

	println(io)
    println(io, "#endif // !defined(SOLOMON_UTIL_IMPL_RETRIEVE_ARGS_HPP)")
end

function main()
    # read options
    argv = parse_cmd()
    N_max = argv["max"]

	output = "impl/retrieve_args.hpp"
	output_dir = dirname(output)
	if !isdir(output_dir)
		mkpath(output_dir)
	end

	open(output, "w") do io
		generate(io, N_max)
	end
end

main()
