using ArgParse
function parse_cmd()
    cfg = ArgParseSettings()
    @add_arg_table cfg begin
        "--max"
        help = "maximum number of clauses to handle"
        arg_type = Int
        default = 32
        "--level"
        help = "maximum number of priority levels"
        arg_type = Int
        default = 1
    end
    return parse_args(cfg)
end

function generate(io::IO, N_max::Int, N_lev::Int)
	# for removal of the trailing comma
	N_generate = N_max + 1

	# Header with update instructions
    println(io, "///")
    println(io, "/// @file solomon/util/impl/sort_clause.hpp")
	println(io, "/// @brief Auto-generated macros for SOLOMON_INTERNAL_SORT_AND_OUTPUT up to $N_max inputs and $N_lev priority levels")
    println(io, "/// @note Generated by sort_clause.jl with --max $N_max --level $N_lev")
	println(io, "/// @note DO NOT EDIT THIS FILE MANUALLY - Regenerate with:")
	println(io, "///       cd solomon/util && julia jl/sort_clause.jl --max $N_max --level $N_lev")
    println(io, "///")
    println(io)
    println(io, "#if !defined(SOLOMON_UTIL_IMPL_SORT_CLAUSE_HPP)")
	println(io, "#define SOLOMON_UTIL_IMPL_SORT_CLAUSE_HPP")
	println(io)

    # generate SOLOMON_INTERNAL_IS_PRIORITY_LEVEL_N
    for ii in 1:N_lev
		println(io)
		println(io, "///")
		println(io, "/// @brief For priority level ", ii)
		println(io, "///")
		println(io, "#define SOLOMON_INTERNAL_IS_PRIORITY_", ii, "_CHECK_", ii, " ~, 1")
		println(io, "#define SOLOMON_INTERNAL_IS_PRIORITY_", ii, "_SECOND(a, b, ...) b")
		println(io, "#define SOLOMON_INTERNAL_IS_PRIORITY_", ii, "_EXPAND(...) SOLOMON_INTERNAL_IS_PRIORITY_", ii, "_SECOND(__VA_ARGS__)")
		println(io, "#define SOLOMON_INTERNAL_IS_PRIORITY_", ii, "_TEST(x) SOLOMON_INTERNAL_IS_PRIORITY_", ii, "_EXPAND(SOLOMON_INTERNAL_CLOAK_CAT(SOLOMON_INTERNAL_IS_PRIORITY_", ii, "_CHECK_, x), 0, )")
		println(io, "#define SOLOMON_INTERNAL_IS_PRIORITY_LEVEL_", ii, "(clause) SOLOMON_INTERNAL_IS_PRIORITY_", ii, "_TEST(SOLOMON_INTERNAL_CLOAK_CAT(SOLOMON_INTERNAL_PRIORITY_LEVEL_, clause))")
    end
	println(io)
	println(io, "///")
	println(io, "/// @brief For priority level 0 (default)")
	println(io, "///")
	print(io, "#define SOLOMON_INTERNAL_IS_PRIORITY_LEVEL_0(clause) SOLOMON_INTERNAL_CLOAK_NOT(")
	for ii in N_lev:-1:2
		print(io, "SOLOMON_INTERNAL_CLOAK_BITOR(SOLOMON_INTERNAL_IS_PRIORITY_LEVEL_", ii, "(clause))(")
	end
	print(io, "SOLOMON_INTERNAL_IS_PRIORITY_LEVEL_1(clause)")
	for ii in 1:N_lev
		print(io, ")")
	end
	println(io)

	# generate SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_N
	println(io)
	println(io, "///")
	println(io, "/// @brief SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_N - Extract all clauses with priority level N")
	println(io, "///")
    for ii in 1:N_lev
		println(io)
		println(io, "///")
		println(io, "/// @brief Priority level ", ii)
		println(io, "///")
		println(io, "#define SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_", ii, "(...) SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_", ii, "_IMPL(__VA_ARGS__)")
		println(io)
		println(io, "#define SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_", ii, "_IMPL(...) SOLOMON_INTERNAL_CLOAK_CAT(SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_", ii, "_IMPL_, SOLOMON_INTERNAL_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)")
		println(io, "#define SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_", ii, "_IMPL_0()")
		for jj in 1:N_generate
			print(io, "#define SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_", ii, "_IMPL_", jj, "(clause1")
			for kk in 2:jj
				print(io, ", clause", kk)
			end
			print(io, ") SOLOMON_INTERNAL_APPEND_CLAUSE(SOLOMON_INTERNAL_IS_PRIORITY_LEVEL_", ii, "(clause1), clause1)")
			if jj > 1
				print(io, " SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_", ii, "_IMPL_", jj - 1, "(")
				for kk in 2:jj
					print(io, "clause", kk)
					if kk < jj
						print(io, ", ")
					end
				end
				print(io, ")")
			end
			println(io)
		end
	end

	# generate SOLOMON_INTERNAL_REMOVE_ALL_PRIORITIZED_IMPL_N
	println(io)
	println(io, "#define SOLOMON_INTERNAL_REMOVE_ALL_PRIORITIZED_IMPL_0()")
	for jj in 1:N_generate
		print(io, "#define SOLOMON_INTERNAL_REMOVE_ALL_PRIORITIZED_IMPL_", jj, "(clause1")
		for kk in 2:jj
			print(io, ", clause", kk)
		end
		print(io, ") SOLOMON_INTERNAL_APPEND_CLAUSE(SOLOMON_INTERNAL_CLOAK_NOT(SOLOMON_INTERNAL_HAS_PRIORITY(clause1)), clause1)")
		if jj > 1
			print(io, " SOLOMON_INTERNAL_REMOVE_ALL_PRIORITIZED_IMPL_", jj - 1, "(")
			for kk in 2:jj
				print(io, "clause", kk)
				if kk < jj
					print(io, ", ")
				end
			end
			print(io, ")")
		end
		println(io)
	end

	# generate SORT_CLAUSE_IMPL_N
	println(io)
	println(io, "#define SOLOMON_INTERNAL_SORT_CLAUSES_IMPL_0()")
	println(io, "#define SOLOMON_INTERNAL_SORT_CLAUSES_IMPL_1(...) __VA_ARGS__")
	for jj in 2:N_generate
		print(io, "#define SOLOMON_INTERNAL_SORT_CLAUSES_IMPL_", jj, "(...)")
		for ii in 1:N_lev
			print(io, " SOLOMON_INTERNAL_EXTRACT_ALL_PRIORITY_", ii, "(__VA_ARGS__)")
		end
		println(io, " SOLOMON_INTERNAL_REMOVE_ALL_PRIORITIZED(__VA_ARGS__)")
	end

	# generate SOLOMON_INTERNAL_STRIP_TRAILING_COMMA_N
	println(io)
	println(io, "#define SOLOMON_INTERNAL_STRIP_TRAILING_COMMA_0()")
	println(io, "#define SOLOMON_INTERNAL_STRIP_TRAILING_COMMA_1(arg1) arg1")
	for jj in 2:N_generate
		print(io, "#define SOLOMON_INTERNAL_STRIP_TRAILING_COMMA_", jj, "(arg1")
		for kk in 2:jj
			print(io, ", arg", kk)
		end
		print(io, ") arg1")
		for kk in 2:jj - 1
			print(io, " arg", kk)
		end
		println(io)
	end

	# define SOLOMON_INTERNAL_SORT_CLAUSES_IMPL(...)
	println(io)
    println(io, "///")
	println(io, "/// @brief Main sorting implementation with reversed priority order")
    println(io, "/// @note Process from highest priority (1) to lower priority (up to $N_lev), then default (0)")
    println(io, "/// @warning Passing more than ", N_max, " clauses will cause a compile error:")
    println(io, "///          - Error message: 'SOLOMON_INTERNAL_SORT_CLAUSES_IMPL_*' was not declared in this scope")
    println(io, "///          - To fix: cd solomon/util && julia jl/sort_clause.jl --max N")
    println(io, "///                   (where N >= your clause count + 1)")
    println(io, "/// @note To increase priority levels, regenerate with:")
	println(io, "///          - cd solomon/util && julia jl/sort_clause.jl --level M")
	println(io, "///                   (where M >= your required priority levels)")
    println(io, "///")
	println(io, "#define SOLOMON_INTERNAL_SORT_CLAUSES_IMPL(...) SOLOMON_INTERNAL_CLOAK_CAT(SOLOMON_INTERNAL_SORT_CLAUSES_IMPL_, SOLOMON_INTERNAL_NUM_ARGS(__VA_ARGS__))(__VA_ARGS__)")

    # # New SOLOMON_INTERNAL_APPEND_CLAUSES with automatic clause sorting
    # println(io)
    # println(io, "///")
    # println(io, "/// @brief Apply automatic clause sorting after checking valid clauses")
    # println(io, "/// @note This moves AS_INDEPENDENT (and equivalents) to the front")
    # println(io, "/// @warning Passing more than ", N_max, " clauses will cause a compile error:")
    # println(io, "///          - Error message: 'SOLOMON_INTERNAL_CHECK_CLAUSE_*' was not declared in this scope")
    # println(io, "///          - To fix: cd solomon/util && julia jl/check_clause.jl --max N")
    # println(io, "///                   (where N >= your clause count)")
    # println(io, "///")
    # println(io, "#define SOLOMON_INTERNAL_APPEND_CLAUSES(...) SOLOMON_INTERNAL_SORT_AND_OUTPUT(SOLOMON_INTERNAL_CHECK_CLAUSE_", N_max, "(__VA_ARGS__))")
    # # Original SOLOMON_INTERNAL_APPEND_CLAUSES without sorting (kept as comment for reference)
    # println(io, "// #define SOLOMON_INTERNAL_APPEND_CLAUSES(...) SOLOMON_INTERNAL_CHECK_CLAUSE_", N_max, "(__VA_ARGS__)")

	println(io)
    println(io, "#endif // !defined(SOLOMON_UTIL_IMPL_SORT_CLAUSE_HPP)")
end

function main()
    # read options
    argv = parse_cmd()
    N_max = argv["max"]
    N_lev = argv["level"]

	output = "impl/sort_clause.hpp"
	output_dir = dirname(output)
	if !isdir(output_dir)
		mkpath(output_dir)
	end

	open(output, "w") do io
		generate(io, N_max, N_lev)
	end
end

main()
