///
/// @file solomon/util/cloak.hpp
/// @author Yohei MIKI (The University of Tokyo)
/// @author Paul Fultz II
/// @brief pickup appropriate clauses for directives
/// @note reference: https://github.com/pfultz2/Cloak/wiki/C-Preprocessor-tricks,-tips,-and-idioms
/// @details implementation is copied from cloak.h developed by Paul Fultz II: available at https://github.com/pfultz2/Cloak (Boost Software License, Version 1.0: https://www.boost.org/LICENSE_1_0.txt)
///
///
#if !defined(SOLOMON_UTIL_CLOAK_HPP)
#define SOLOMON_UTIL_CLOAK_HPP

// copied from cloak.h developed by Paul Fultz II: available at https://github.com/pfultz2/Cloak (Boost Software License, Version 1.0: https://www.boost.org/LICENSE_1_0.txt)
// difference from the original version: rename the name of macros

#define SOLOMON_INTERNAL_CLOAK_CAT(a, ...) SOLOMON_INTERNAL_CLOAK_IMPL_CAT(a, __VA_ARGS__)
#define SOLOMON_INTERNAL_CLOAK_IMPL_CAT(a, ...) a##__VA_ARGS__

#define SOLOMON_INTERNAL_CLOAK_COMPL(b) SOLOMON_INTERNAL_CLOAK_IMPL_CAT(SOLOMON_INTERNAL_CLOAK_COMPL_, b)
#define SOLOMON_INTERNAL_CLOAK_COMPL_0 1
#define SOLOMON_INTERNAL_CLOAK_COMPL_1 0

#define SOLOMON_INTERNAL_CLOAK_BITAND(x) SOLOMON_INTERNAL_CLOAK_IMPL_CAT(SOLOMON_INTERNAL_CLOAK_BITAND_, x)
#define SOLOMON_INTERNAL_CLOAK_BITAND_0(y) 0
#define SOLOMON_INTERNAL_CLOAK_BITAND_1(y) y

#define SOLOMON_INTERNAL_CLOAK_BITOR(x) SOLOMON_INTERNAL_CLOAK_IMPL_CAT(SOLOMON_INTERNAL_CLOAK_BITOR_, x)
#define SOLOMON_INTERNAL_CLOAK_BITOR_0(y) y
#define SOLOMON_INTERNAL_CLOAK_BITOR_1(y) 1

#define SOLOMON_INTERNAL_CLOAK_CHECK_N(x, n, ...) n
#define SOLOMON_INTERNAL_CLOAK_CHECK(...) SOLOMON_INTERNAL_CLOAK_CHECK_N(__VA_ARGS__, 0, )
#define SOLOMON_INTERNAL_CLOAK_PROBE(x) x, 1,

#define SOLOMON_INTERNAL_CLOAK_IS_PAREN(x) SOLOMON_INTERNAL_CLOAK_CHECK(SOLOMON_INTERNAL_CLOAK_IS_PAREN_PROBE x)
#define SOLOMON_INTERNAL_CLOAK_IS_PAREN_PROBE(...) SOLOMON_INTERNAL_CLOAK_PROBE(~)

#define SOLOMON_INTERNAL_CLOAK_NOT(x) SOLOMON_INTERNAL_CLOAK_CHECK(SOLOMON_INTERNAL_CLOAK_IMPL_CAT(SOLOMON_INTERNAL_CLOAK_NOT_, x))
#define SOLOMON_INTERNAL_CLOAK_NOT_0 SOLOMON_INTERNAL_CLOAK_PROBE(~)

#define SOLOMON_INTERNAL_CLOAK_BOOL(x) SOLOMON_INTERNAL_CLOAK_COMPL(SOLOMON_INTERNAL_CLOAK_NOT(x))

#define SOLOMON_INTERNAL_CLOAK_IIF(c) SOLOMON_INTERNAL_CLOAK_IMPL_CAT(SOLOMON_INTERNAL_CLOAK_IIF_, c)
#define SOLOMON_INTERNAL_CLOAK_IIF_0(t, ...) __VA_ARGS__
#define SOLOMON_INTERNAL_CLOAK_IIF_1(t, ...) t

#define SOLOMON_INTERNAL_CLOAK_IF(c) SOLOMON_INTERNAL_CLOAK_IIF(SOLOMON_INTERNAL_CLOAK_BOOL(c))

#define SOLOMON_INTERNAL_CLOAK_EAT(...)

#define SOLOMON_INTERNAL_CLOAK_IMPL_COMPARE(x, y) SOLOMON_INTERNAL_CLOAK_IS_PAREN(COMPARE_##x(COMPARE_##y)(()))

#define SOLOMON_INTERNAL_CLOAK_IS_COMPARABLE(x) SOLOMON_INTERNAL_CLOAK_IS_PAREN(SOLOMON_INTERNAL_CLOAK_CAT(COMPARE_, x)(()))

#define SOLOMON_INTERNAL_CLOAK_NOT_EQUAL(x, y) SOLOMON_INTERNAL_CLOAK_IIF(SOLOMON_INTERNAL_CLOAK_BITAND(SOLOMON_INTERNAL_CLOAK_IS_COMPARABLE(x))(SOLOMON_INTERNAL_CLOAK_IS_COMPARABLE(y)))(SOLOMON_INTERNAL_CLOAK_IMPL_COMPARE, 1 SOLOMON_INTERNAL_CLOAK_EAT)(x, y)

#define SOLOMON_INTERNAL_CLOAK_EQUAL(x, y) SOLOMON_INTERNAL_CLOAK_COMPL(SOLOMON_INTERNAL_CLOAK_NOT_EQUAL(x, y))

#endif  // !defined(SOLOMON_UTIL_CLOAK_HPP)
