///
/// @file solomon/util/pickup.hpp
/// @author Yohei MIKI (The University of Tokyo)
/// @brief pickup appropriate clauses for directives
///
/// @copyright Copyright (c) 2024 Yohei MIKI
///
/// The MIT License is applied to this software, see LICENSE.txt
///
#if !defined(SOLOMON_UTIL_PICKUP_HPP)
#define SOLOMON_UTIL_PICKUP_HPP

#include "cloak.hpp"
#include "va_args.hpp"
#include "sort.hpp"

///
/// @brief logical or
///
#define SOLOMON_INTERNAL_PICKUP_BITOR(x) SOLOMON_INTERNAL_CLOAK_IMPL_CAT(SOLOMON_INTERNAL_PICKUP_BITOR_, x)
#define SOLOMON_INTERNAL_PICKUP_BITOR_0(y) y
#define SOLOMON_INTERNAL_PICKUP_BITOR_1(y) 1

///
/// @brief flag matching
///
#define SOLOMON_INTERNAL_PICKUP_FLAG_MATCHING(directive_tag, ...) SOLOMON_INTERNAL_CLOAK_CAT(SOLOMON_INTERNAL_PICKUP_FLAG_MATCHING_, SOLOMON_INTERNAL_NUM_ARGS(__VA_ARGS__))(directive_tag, __VA_ARGS__)

#include "impl/pickup_clause.hpp"// include SOLOMON_INTERNAL_PICKUP_CLAUSE_N(...), SOLOMON_INTERNAL_PICKUP_EXPAND_FLAGS_N(...), and SOLOMON_INTERNAL_PICKUP_FLAG_MATCHING_N(...) from auto-generated file
#include "impl/check_clause.hpp"// include SOLOMON_INTERNAL_APPEND_CLAUSES(...) from auto-generated file

// original SOLOMON_INTERNAL_APPEND_CLAUSE implementation (works without automatic clause sorting)
// #define SOLOMON_INTERNAL_APPEND_CLAUSE(flag, clause) SOLOMON_INTERNAL_CLOAK_IF(flag)(clause)

#define SOLOMON_INTERNAL_APPEND_MATCHED_CLAUSE_IMPL(NUM, ...) SOLOMON_INTERNAL_CLOAK_CAT(SOLOMON_INTERNAL_PICKUP_CLAUSE_, NUM)(__VA_ARGS__)
#define SOLOMON_INTERNAL_APPEND_MATCHED_CLAUSE(...) SOLOMON_INTERNAL_APPEND_MATCHED_CLAUSE_IMPL(__VA_ARGS__)

// N, dtag1, dtag2, ..., dtagN, clause1, Nc1, ctag1_1, ..., ctag1_Nc1, clause2, Nc2, ctag2_1, ..., ctag2_Nc2, ...
#define SOLOMON_INTERNAL_PICKUP_DIRECTIVE_TAGS(...) SOLOMON_INTERNAL_EXTRACT_ARGS(__VA_ARGS__)
#define SOLOMON_INTERNAL_PICKUP_CLAUSE_ARGS(...) SOLOMON_INTERNAL_RETRIEVE_ARGS(__VA_ARGS__)
#define SOLOMON_INTERNAL_PICKUP_IMPL_CLAUSE_CANDIDATE(clause, ...) clause, SOLOMON_INTERNAL_EXTRACT_ARGS(__VA_ARGS__)
#define SOLOMON_INTERNAL_PICKUP_CLAUSE_CANDIDATE(...) SOLOMON_INTERNAL_PICKUP_IMPL_CLAUSE_CANDIDATE(__VA_ARGS__)
#define SOLOMON_INTERNAL_PICKUP_IMPL_RETRIEVE_CLAUSE_CANDIDATE(clause, ...) SOLOMON_INTERNAL_RETRIEVE_ARGS(__VA_ARGS__)
#define SOLOMON_INTERNAL_PICKUP_RETRIEVE_CLAUSE_CANDIDATE(...) SOLOMON_INTERNAL_PICKUP_IMPL_RETRIEVE_CLAUSE_CANDIDATE(__VA_ARGS__)

#define COMPARE_0(x) x
#define SOLOMON_INTERNAL_NOT_VOID(...) SOLOMON_INTERNAL_CLOAK_NOT(SOLOMON_INTERNAL_CLOAK_EQUAL(0, SOLOMON_INTERNAL_NUM_ARGS(__VA_ARGS__)))
#define SOLOMON_INTERNAL_CHECK_CLAUSE(...) SOLOMON_INTERNAL_CLOAK_IF(SOLOMON_INTERNAL_NOT_VOID(SOLOMON_INTERNAL_PICKUP_CLAUSE_ARGS(__VA_ARGS__)))(SOLOMON_INTERNAL_APPEND_MATCHED_CLAUSE(SOLOMON_INTERNAL_ARGS_WITH_NUM(SOLOMON_INTERNAL_PICKUP_DIRECTIVE_TAGS(__VA_ARGS__)), SOLOMON_INTERNAL_PICKUP_CLAUSE_CANDIDATE(SOLOMON_INTERNAL_PICKUP_CLAUSE_ARGS(__VA_ARGS__))))

#endif  // !defined(SOLOMON_UTIL_PICKUP_HPP)
