///
/// @file solomon/serial/fallback.hpp
/// @author Yohei MIKI (The University of Tokyo)
/// @brief empty definitions of all directive macros for serial execution (neither OpenACC nor OpenMP is available)
///
/// @note without this header, directive macros would remain unexpanded and break compilation when neither _OPENACC nor _OPENMP is defined
///
/// @copyright Copyright (c) 2024 Yohei MIKI
///
/// The MIT License is applied to this software, see LICENSE.txt
///
#if !defined(SOLOMON_SERIAL_FALLBACK_HPP)
#define SOLOMON_SERIAL_FALLBACK_HPP

// directive macros taking clauses (expand to nothing in serial execution)
#define PRAGMA_ACC(...)
#define PRAGMA_ACC_ATOMIC(...)
#define PRAGMA_ACC_CACHE(...)
#define PRAGMA_ACC_DATA(...)
#define PRAGMA_ACC_DATA_PRESENT(...)
#define PRAGMA_ACC_DECLARE(...)
#define PRAGMA_ACC_ENTER_DATA(...)
#define PRAGMA_ACC_ENTER_DATA_COPYIN(...)
#define PRAGMA_ACC_ENTER_DATA_CREATE(...)
#define PRAGMA_ACC_EXIT_DATA(...)
#define PRAGMA_ACC_EXIT_DATA_COPYOUT(...)
#define PRAGMA_ACC_EXIT_DATA_DELETE(...)
#define PRAGMA_ACC_HOST_DATA(...)
#define PRAGMA_ACC_HOST_DATA_USE_DEVICE(...)
#define PRAGMA_ACC_KERNELS(...)
#define PRAGMA_ACC_KERNELS_LOOP(...)
#define PRAGMA_ACC_LAUNCH_DEFAULT(...)
#define PRAGMA_ACC_LOOP(...)
#define PRAGMA_ACC_OFFLOADING_DEFAULT(...)
#define PRAGMA_ACC_PARALLEL(...)
#define PRAGMA_ACC_PARALLEL_LOOP(...)
#define PRAGMA_ACC_ROUTINE(...)
#define PRAGMA_ACC_SERIAL(...)
#define PRAGMA_ACC_UPDATE(...)
#define PRAGMA_ACC_UPDATE_DEVICE(...)
#define PRAGMA_ACC_UPDATE_HOST(...)
#define PRAGMA_ACC_WAIT(...)
#define PRAGMA_OMP(...)
#define PRAGMA_OMP_ATOMIC(...)
#define PRAGMA_OMP_BEGIN_DECLARE_TARGET(...)
#define PRAGMA_OMP_CRITICAL(...)
#define PRAGMA_OMP_DECLARE_SIMD(...)
#define PRAGMA_OMP_DECLARE_TARGET(...)
#define PRAGMA_OMP_DEPOBJ(...)
#define PRAGMA_OMP_DISTRIBUTE(...)
#define PRAGMA_OMP_DISTRIBUTE_PARALLEL_DO(...)
#define PRAGMA_OMP_DISTRIBUTE_PARALLEL_DO_SIMD(...)
#define PRAGMA_OMP_DISTRIBUTE_PARALLEL_FOR(...)
#define PRAGMA_OMP_DISTRIBUTE_PARALLEL_FOR_SIMD(...)
#define PRAGMA_OMP_DISTRIBUTE_SIMD(...)
#define PRAGMA_OMP_DO(...)
#define PRAGMA_OMP_DO_SIMD(...)
#define PRAGMA_OMP_FLUSH(...)
#define PRAGMA_OMP_FOR(...)
#define PRAGMA_OMP_FOR_SIMD(...)
#define PRAGMA_OMP_INTEROP(...)
#define PRAGMA_OMP_LOOP(...)
#define PRAGMA_OMP_MASKED(...)
#define PRAGMA_OMP_MASKED_TASKLOOP(...)
#define PRAGMA_OMP_MASKED_TASKLOOP_SIMD(...)
#define PRAGMA_OMP_ORDERED(...)
#define PRAGMA_OMP_PARALLEL(...)
#define PRAGMA_OMP_PARALLEL_DO(...)
#define PRAGMA_OMP_PARALLEL_DO_SIMD(...)
#define PRAGMA_OMP_PARALLEL_FOR(...)
#define PRAGMA_OMP_PARALLEL_FOR_SIMD(...)
#define PRAGMA_OMP_PARALLEL_LOOP(...)
#define PRAGMA_OMP_PARALLEL_MASKED_TASKLOOP(...)
#define PRAGMA_OMP_PARALLEL_MASKED_TASKLOOP_SIMD(...)
#define PRAGMA_OMP_PARALLEL_SECTIONS(...)
#define PRAGMA_OMP_SCAN(...)
#define PRAGMA_OMP_SCOPE(...)
#define PRAGMA_OMP_SECTIONS(...)
#define PRAGMA_OMP_SIMD(...)
#define PRAGMA_OMP_SINGLE(...)
#define PRAGMA_OMP_TARGET(...)
#define PRAGMA_OMP_TARGET_ATOMIC(...)
#define PRAGMA_OMP_TARGET_DATA(...)
#define PRAGMA_OMP_TARGET_DATA_USE_DEVICE_ADDR(...)
#define PRAGMA_OMP_TARGET_DATA_USE_DEVICE_PTR(...)
#define PRAGMA_OMP_TARGET_ENTER_DATA(...)
#define PRAGMA_OMP_TARGET_ENTER_DATA_MAP_ALLOC(...)
#define PRAGMA_OMP_TARGET_ENTER_DATA_MAP_TO(...)
#define PRAGMA_OMP_TARGET_EXIT_DATA(...)
#define PRAGMA_OMP_TARGET_EXIT_DATA_MAP_DELETE(...)
#define PRAGMA_OMP_TARGET_EXIT_DATA_MAP_FROM(...)
#define PRAGMA_OMP_TARGET_LAUNCH_DEFAULT(...)
#define PRAGMA_OMP_TARGET_OFFLOADING_DEFAULT(...)
#define PRAGMA_OMP_TARGET_PARALLEL(...)
#define PRAGMA_OMP_TARGET_PARALLEL_DO(...)
#define PRAGMA_OMP_TARGET_PARALLEL_DO_SIMD(...)
#define PRAGMA_OMP_TARGET_PARALLEL_FOR(...)
#define PRAGMA_OMP_TARGET_PARALLEL_FOR_SIMD(...)
#define PRAGMA_OMP_TARGET_PARALLEL_LOOP(...)
#define PRAGMA_OMP_TARGET_SIMD(...)
#define PRAGMA_OMP_TARGET_TASKWAIT(...)
#define PRAGMA_OMP_TARGET_TEAMS(...)
#define PRAGMA_OMP_TARGET_TEAMS_DISTRIBUTE(...)
#define PRAGMA_OMP_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO(...)
#define PRAGMA_OMP_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD(...)
#define PRAGMA_OMP_TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR(...)
#define PRAGMA_OMP_TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD(...)
#define PRAGMA_OMP_TARGET_TEAMS_DISTRIBUTE_SIMD(...)
#define PRAGMA_OMP_TARGET_TEAMS_LOOP(...)
#define PRAGMA_OMP_TARGET_UPDATE(...)
#define PRAGMA_OMP_TARGET_UPDATE_FROM(...)
#define PRAGMA_OMP_TARGET_UPDATE_TO(...)
#define PRAGMA_OMP_TASK(...)
#define PRAGMA_OMP_TASKGROUP(...)
#define PRAGMA_OMP_TASKLOOP(...)
#define PRAGMA_OMP_TASKLOOP_SIMD(...)
#define PRAGMA_OMP_TASKWAIT(...)
#define PRAGMA_OMP_TEAMS(...)
#define PRAGMA_OMP_TEAMS_DISTRIBUTE(...)
#define PRAGMA_OMP_TEAMS_DISTRIBUTE_PARALLEL_DO(...)
#define PRAGMA_OMP_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD(...)
#define PRAGMA_OMP_TEAMS_DISTRIBUTE_PARALLEL_FOR(...)
#define PRAGMA_OMP_TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD(...)
#define PRAGMA_OMP_TEAMS_DISTRIBUTE_SIMD(...)
#define PRAGMA_OMP_TEAMS_LOOP(...)
#define PRAGMA_OMP_THREADPRIVATE(...)
#define PRAGMA_OMP_TILE(...)
#define PRAGMA_OMP_UNROLL(...)
#define PRAGMA_OMP_WORKSHARE(...)
#define PRAGMA_STR(...)
#define PRAGMA_STR1(...)

// directive macros without arguments (expand to nothing in serial execution)
#define PRAGMA_ACC_ATOMIC_CAPTURE
#define PRAGMA_ACC_ATOMIC_READ
#define PRAGMA_ACC_ATOMIC_UPDATE
#define PRAGMA_ACC_ATOMIC_WRITE
#define PRAGMA_ACC_END_DATA
#define PRAGMA_ACC_END_HOST_DATA
#define PRAGMA_ACC_END_KERNELS
#define PRAGMA_ACC_END_LAUNCH_DEFAULT
#define PRAGMA_ACC_END_OFFLOADING_DEFAULT
#define PRAGMA_ACC_END_PARALLEL
#define PRAGMA_ACC_END_ROUTINE
#define PRAGMA_ACC_END_SERIAL
#define PRAGMA_OMP_ATOMIC_CAPTURE
#define PRAGMA_OMP_ATOMIC_READ
#define PRAGMA_OMP_ATOMIC_UPDATE
#define PRAGMA_OMP_ATOMIC_WRITE
#define PRAGMA_OMP_BARRIER
#define PRAGMA_OMP_END_CRITICAL
#define PRAGMA_OMP_END_DECLARE_TARGET
#define PRAGMA_OMP_END_PARALLEL
#define PRAGMA_OMP_END_PARALLEL_SECTIONS
#define PRAGMA_OMP_END_SECTIONS
#define PRAGMA_OMP_END_SIMD
#define PRAGMA_OMP_END_SINGLE
#define PRAGMA_OMP_END_TARGET
#define PRAGMA_OMP_END_TARGET_DATA
#define PRAGMA_OMP_END_TARGET_PARALLEL
#define PRAGMA_OMP_END_TARGET_SIMD
#define PRAGMA_OMP_END_TARGET_TEAMS
#define PRAGMA_OMP_END_TEAMS
#define PRAGMA_OMP_SECTION
#define PRAGMA_OMP_TARGET_ATOMIC_CAPTURE
#define PRAGMA_OMP_TARGET_ATOMIC_READ
#define PRAGMA_OMP_TARGET_ATOMIC_UPDATE
#define PRAGMA_OMP_TARGET_ATOMIC_WRITE
#define PRAGMA_OMP_TASKYIELD

#endif  // !defined(SOLOMON_SERIAL_FALLBACK_HPP)
